//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employeeSalary
    {
        public long TransactionId { get; set; }
        public int EmployeeId { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string SalaryMonth { get; set; }
    }
}
